vim.g.mapleader = " "
vim.keymap.set("n", "<leader>cd", vim.cmd.Ex)
vim.keymap.set({"n", "v"}, "y", [["+y]])
vim.keymap.set("n", "Y", [["+Y]])
vim.keymap.set({"n", "v"}, "p", [["+p]])
vim.keymap.set("n", "P", [["+P]])
vim.keymap.set('n', '<C-Left>', '<C-w>h', { desc = 'Okno w lewo' })
vim.keymap.set('n', '<C-Right>', '<C-w>l', { desc = 'Okno w prawo' })
vim.keymap.set('n', '<C-Up>', '<C-w>k', { desc = 'Okno w górę' })
vim.keymap.set('n', '<C-Down>', '<C-w>j', { desc = 'Okno w dół' })
vim.keymap.set('t', '<C-Left>', [[<C-\><C-n><C-w>h]], { desc = 'Wyjdź z terminala w lewo' })
vim.keymap.set('t', '<C-Right>', [[<C-\><C-n><C-w>l]], { desc = 'Wyjdź z terminala w prawo' })
vim.keymap.set('t', '<C-Up>', [[<C-\><C-n><C-w>k]], { desc = 'Wyjdź z terminala w górę' })
vim.keymap.set('t', '<C-Down>', [[<C-\><C-n><C-w>j]], { desc = 'Wyjdź z terminala w dół' })
vim.keymap.set('t', '<Esc>', [[<C-\><C-n>]], { desc = 'Tryb normalny w terminalu' })
